### PR TITLE
Fixed problem for isClosed.

### LINKED ISSUE #229: Curve.IsClosed fails if curve is periodic
We should check if t0.0 and t1.0 are coincident.
https://github.com/mcneel/opennurbs/blob/484ba88836bbedff8fe0b9e574fcd6434b49c21c/opennurbs_curve.cpp#L569

### PR DESCRIPTION
**Pull request by sonomirco**
Refactor some tests.

### What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ Feature
- [X] 🐛 Bug Fix
- [ ] 👷 Optimization
- [ ] 📝 Documentation Update
- [ ] 🔖 Release
- [ ] 🚩 Other

### Description

This PR fixes the bug ``isClosed`` method.

### Related Tickets & Documents

This PR closes #229 

### Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📓 docs
- [X] 🙅 no documentation needed

### CODE REVIEW

File: src/GShark/Geometry/NurbsCurve.cs [hunk 1]
```diff
@@ -138,7 +138,9 @@ public BoundingBox BoundingBox
         /// <returns>True if the curve is closed.</returns>
         public bool IsClosed()
         {
-            return !(LocationPoints[0].DistanceTo(LocationPoints[LocationPoints.Count - 1]) > 0);
```
Comment (d3ssy) [inline src/GShark/Geometry/NurbsCurve.cs:141]: I implemented tolerance in the equality check for Point3, so you can just use == operator.

File: src/GShark/Geometry/NurbsCurve.cs [hunk 2]
```diff
@@ -138,7 +138,9 @@ public BoundingBox BoundingBox
...
+            Point3 pt0 = Evaluation.CurvePointAt(this,0.0);
```
Comment (d3ssy) [inline src/GShark/Geometry/NurbsCurve.cs:141]: Use domain.T0 and T1 instead? in case crv is not reparam?
